# Generated by Django 5.1.2 on 2024-12-19 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=100)),
                ('bet_result', models.IntegerField()),
                ('p_hand_sum', models.PositiveIntegerField()),
                ('d_hand_sum', models.PositiveIntegerField()),
                ('p_hand_img', models.CharField(max_length=200)),
                ('d_hand_img', models.CharField(max_length=200)),
                ('played_date', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bj.room')),
            ],
        ),
    ]
